/*
 * clk_output.c
 *
 *  Created on: Dec 13, 2019
 *      Author: jains
 */

#include "clk_output.h"

void clock_output()
{

	CMU->CTRL |= CLKOUTSEL1((CLKOUTSEL & HFXO));
	CMU->CTRL |= CLKOUTSEL0(CLKOUTSEL & LFXO);

	CMU->ROUTEPEN |= CMU_ROUTEPEN_CLKOUT1PEN;
	CMU->ROUTEPEN |= CMU_ROUTEPEN_CLKOUT0PEN;

	CMU->ROUTELOC0 = (CMU->ROUTELOC0
					& (~CMU_ROUTELOC0_CLKOUT0LOC(CMU_ROUTELOC0_CLKOUTLOC_MASK)))
					| CMU_ROUTELOC0_CLKOUT0LOC(CMU_ROUTELOC_LOC2);
	CMU->ROUTELOC0 = (CMU->ROUTELOC0
					& (~CMU_ROUTELOC0_CLKOUT1LOC(CMU_ROUTELOC0_CLKOUTLOC_MASK)))
					| CMU_ROUTELOC0_CLKOUT1LOC(CMU_ROUTELOC_LOC2);

}
